### ISSUE TITLE
Generated Protobuf definitions have invalid field numbers

### ISSUE THREAD

**Issue by johansen** [karissa/jsonschema-protobuf#2]
According to [the Protobuf 2 spec](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec), field numbers must begin with digits 1-9. However, jsonschema-protobuf 1.0.1 (as deployed in NPM) generates field number 0. This even shows up in the example on the package documentation: https://www.npmjs.com/package/jsonschema-protobuf

The result is that the generated Protobuf definition won't compile, getting the "Field numbers must be positive integers" error. This is using `protoc` 2.6.1.

**Comment by okdistribute** [comment]
A fix is now published as 1.0.2, should output starting with field number 1 now. Thanks for the ping!
